import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile(x3dpsail.SFString("Immersive")).setVersion(x3dpsail.SFString("3.3"))
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("abox.x3d")).setName(x3dpsail.SFString("title")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("John Carlson")).setName(x3dpsail.SFString("creator")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("manual")).setName(x3dpsail.SFString("generator")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("https://coderextreme.net/X3DJSONLD/abox.x3d")).setName(x3dpsail.SFString("identifier")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("a box")).setName(x3dpsail.SFString("description"))))
      .setScene(x3dpsail.Scene()
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("anyShape"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setAccessType(x3dpsail.SFString("inputOutput")).setName(x3dpsail.SFString("myShape")).setType(x3dpsail.SFString("MFNode"))
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Sphere()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .setIS(x3dpsail.IS()
                .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("children")).setProtoField(x3dpsail.SFString("myShape")))))))
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("one"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setAccessType(x3dpsail.SFString("inputOutput")).setName(x3dpsail.SFString("myShape")).setType(x3dpsail.SFString("MFNode"))
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Cylinder()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("anyShape"))
                .setIS(x3dpsail.IS()
                  .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("myShape")).setProtoField(x3dpsail.SFString("myShape"))))))))
        .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("one"))
          .addFieldValue(x3dpsail.fieldValue().setName(x3dpsail.SFString("myShape"))
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Box().setSize(x3dpsail.SFVec3f(140,140,140))))))))

X3D0.toFileX3D("abox_RoundTrip.x3d")
