import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile("Immersive").setVersion("3.3")
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("title")).setContent("abox.x3d"))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("creator")).setContent("John Carlson"))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("generator")).setContent("manual"))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("identifier")).setContent("https://coderextreme.net/X3DJSONLD/abox.x3d"))
        .addMeta(x3dpsail.meta().setName(x3dpsail.SFString("description")).setContent("a box")))
      .setScene(x3dpsail.Scene()
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("anyShape"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName(x3dpsail.SFString("myShape")).setAccessType("inputOutput").setType("MFNode")
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Sphere()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .setIS(x3dpsail.IS()
                .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("children")).setProtoField(x3dpsail.SFString("myShape")))))))
        .addChild(x3dpsail.ProtoDeclare().setName(x3dpsail.SFString("one"))
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName(x3dpsail.SFString("myShape")).setAccessType("inputOutput").setType("MFNode")
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Cylinder()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("anyShape"))
                .setIS(x3dpsail.IS()
                  .addConnect(x3dpsail.connect().setNodeField(x3dpsail.SFString("myShape")).setProtoField(x3dpsail.SFString("myShape"))))))))
        .addChild(x3dpsail.ProtoInstance().setName(x3dpsail.SFString("one"))
          .addFieldValue(x3dpsail.fieldValue().setName(x3dpsail.SFString("myShape"))
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Box().setSize([140,140,140])))))))

X3D0.toFileX3D("abox_RoundTrip.x3d")
