import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile("Immersive").setVersion("3.3")
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setName("title").setContent("abox.x3d"))
        .addMeta(x3dpsail.meta().setName("creator").setContent("John Carlson"))
        .addMeta(x3dpsail.meta().setName("generator").setContent("manual"))
        .addMeta(x3dpsail.meta().setName("identifier").setContent("https://coderextreme.net/X3DJSONLD/abox.x3d"))
        .addMeta(x3dpsail.meta().setName("description").setContent("a box")))
      .setScene(x3dpsail.Scene()
        .addChild(x3dpsail.ProtoDeclare().setName("anyShape")
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName("myShape").setAccessType("inputOutput").setType("MFNode")
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Sphere()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .setIS(x3dpsail.IS()
                .addConnect(x3dpsail.connect().setNodeField("children").setProtoField("myShape"))))))
        .addChild(x3dpsail.ProtoDeclare().setName("one")
          .setProtoInterface(x3dpsail.ProtoInterface()
            .addField(x3dpsail.field().setName("myShape").setAccessType("inputOutput").setType("MFNode")
              .addChild(x3dpsail.Shape()
                .setGeometry(x3dpsail.Cylinder()))))
          .setProtoBody(x3dpsail.ProtoBody()
            .addChild(x3dpsail.Transform()
              .addChild(x3dpsail.ProtoInstance().setName("anyShape")
                .setIS(x3dpsail.IS()
                  .addConnect(x3dpsail.connect().setNodeField("myShape").setProtoField("myShape")))))))
        .addChild(x3dpsail.ProtoInstance().setName("one")
          .addFieldValue(x3dpsail.fieldValue().setName("myShape")
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Box().setSize(140,140,140)))))))

X3D0.toFileX3D("abox_RoundTrip.x3d")
