from X3Dpackage import *
X3D0 = X3D()
X3D0.setProfile("Immersive")
X3D0.setVersion("3.1")
head1 = head()
meta2 = meta()
meta2.setContent("CleatClamp.MeshLab.x3d")
meta2.setName("title")
head1.addMeta(meta2)
meta3 = meta()
meta3.setContent("Generated from Meshlab X3D Exported")
meta3.setName("description")
head1.addMeta(meta3)
meta4 = meta()
meta4.setContent("19 June 2019")
meta4.setName("created")
head1.addMeta(meta4)
meta5 = meta()
meta5.setContent("Meshlab X3D Exported, http://meshlab.sourceforge.net")
meta5.setName("generator")
head1.addMeta(meta5)
X3D0.setHead(head1)
Scene6 = Scene()
Shape7 = Shape()
IndexedFaceSet8 = IndexedFaceSet(solid = False)
Coordinate9 = Coordinate()
IndexedFaceSet8.setCoord(Coordinate9)
Shape7.setGeometry(IndexedFaceSet8)
Scene6.addChildren(Shape7)
X3D0.setScene(Scene6)
