import x3dpsail


X3D0 = (x3dpsail.X3D().setProfile(x3dpsail.SFString("Immersive")).setVersion(x3dpsail.SFString("3.3"))
      .setHead(x3dpsail.head()
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.x3d")).setName(x3dpsail.SFString("title")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("Simple X3D scene example: Hello World!")).setName(x3dpsail.SFString("description")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("30 October 2000")).setName(x3dpsail.SFString("created")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("28 July 2015")).setName(x3dpsail.SFString("modified")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("Don Brutzman")).setName(x3dpsail.SFString("creator")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.tall.png")).setName(x3dpsail.SFString("Image")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://en.wikipedia.org/wiki/Hello_world")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("https://en.wikipedia.org/wiki/Hello#.22Hello.2C_World.22_computer_program")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("https://en.wikipedia.org/wiki/\"Hello,_World!\"_program")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://en.wikibooks.org/w/index.php?title=Computer_Programming/Hello_world")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://www.HelloWorldExample.net")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://www.web3D.org")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://www.web3d.org/realtime-3d/news/internationalization-x3d")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://www.web3d.org/x3d/content/examples/HelloWorld.x3d")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://X3dGraphics.com/examples/X3dForAdvancedModeling/HelloWorldScenes")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter01TechnicalOverview/HelloWorld.x3d")).setName(x3dpsail.SFString("identifier")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("http://www.web3d.org/x3d/content/examples/license.html")).setName(x3dpsail.SFString("license")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit")).setName(x3dpsail.SFString("generator")))
        # Alternate encodings: VRML97, X3D ClassicVRML Encoding, X3D Compressed Binary Encoding (CBE), X3DOM, JSON 

        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.wrl")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.x3dv")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.x3db")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.xhtml")).setName(x3dpsail.SFString("reference")))
        .addMeta(x3dpsail.meta().setContent(x3dpsail.SFString("HelloWorld.json")).setName(x3dpsail.SFString("reference"))))
      .setScene(x3dpsail.Scene()
        # Example scene to illustrate X3D nodes and fields (XML elements and attributes) 

        .addChild(x3dpsail.Group()
          .addChild(x3dpsail.Viewpoint().setDEF(x3dpsail.SFString("ViewUpClose")).setCenterOfRotation(x3dpsail.SFVec3f(0,-1,0)).setDescription(x3dpsail.SFString("Hello world!")).setPosition(x3dpsail.SFVec3f(0,-1,7)))
          .addChild(x3dpsail.Transform().setRotation(x3dpsail.SFRotation(0,1,0,3))
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Sphere())
              .setAppearance(x3dpsail.Appearance()
                .setMaterial(x3dpsail.Material().setDEF(x3dpsail.SFString("MaterialLightBlue")).setDiffuseColor(x3dpsail.SFColor(0.1,0.5,1)))
                .setTexture(x3dpsail.ImageTexture().setDEF(x3dpsail.SFString("ImageCloudlessEarth")).setUrl(x3dpsail.MFString(["earth-topo.png","earth-topo.jpg","earth-topo-small.gif","http://www.web3d.org/x3d/content/examples/Basic/earth-topo.png","http://www.web3d.org/x3d/content/examples/Basic/earth-topo.jpg","http://www.web3d.org/x3d/content/examples/Basic/earth-topo-small.gif"]))))))
          .addChild(x3dpsail.Transform().setTranslation(x3dpsail.SFVec3f(0,-2,0))
            .addChild(x3dpsail.Shape()
              .setGeometry(x3dpsail.Text().setDEF(x3dpsail.SFString("TextMessage")).setString(x3dpsail.MFString(["Hello","world!"]))
                .setFontStyle(x3dpsail.FontStyle().setJustify(x3dpsail.MFString(["MIDDLE","MIDDLE"]))))
              .setAppearance(x3dpsail.Appearance()
                .setMaterial(x3dpsail.Material().setUSE(x3dpsail.SFString("MaterialLightBlue")))))))))

X3D0.toFileX3D("HelloWorld_RoundTrip.x3d")
