import jnius_config
jnius_config.set_classpath('.', '../../../jars/X3DJSAIL.3.3.full.jar')
from jnius import autoclass
from X3Dpackage import *
X3D0 = (X3D() 
   .setProfile("Immersive") 
   .setVersion("3.1") 
   .setHead(head()    .addMeta(meta()     .setContent("CleatClamp.MeshLab.x3d") 
     .setName("title") 
    ) 
    .addMeta(meta()     .setContent("Generated from Meshlab X3D Exported") 
     .setName("description") 
    ) 
    .addMeta(meta()     .setContent("19 June 2019") 
     .setName("created") 
    ) 
    .addMeta(meta()     .setContent("Meshlab X3D Exported, http://meshlab.sourceforge.net") 
     .setName("generator") 
    ) 
   ) 
   .setScene(Scene()    .addChildren([Shape()     .setGeometry(IndexedFaceSet()      .setCoord(Coordinate(solid = False)      ) 
     ) 
]    ) 
   ) 
)